services:

  bd:
    image: mongo:latest
    volumes:
      - ./db_data:/data/db
    ports:
      - 27017:27017

  backend:
    image: node:20.18-slim
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app:cached
    command:
      - sh
      - -c
      - |
        npm i
        npm run start:dev
    ports:
      - 3000:3000
  frontend:
    image: node:20.18-slim
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev
    stdin_open: true # docker run -i #
    tty: true        # docker run -t
    restart: always
    ports:
      - 5000:5173
